runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: assets 
  
- url: /(.+)
  static_files: assets/\1
  upload: assets/(.*)

- url: .*
  script: Main.application

# - url: /guava-strips\.js
#   static_files: assets/guava-strips.js
#   upload: assets/guava-strips\.js

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest