runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /assets
  static_dir: assets 
  
- url: /(.+)
  static_files: assets/\1
  upload: assets/(.*)

- url: /
  script: Main.application

- url: /vibehome
  script: Main.application



libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest