runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets 
  
- url: /(.+)
  static_files: assets/\1
  upload: assets/(.*)

- url: /
  script: Main.application
<<<<<<< HEAD
=======

>>>>>>> 785407ad353e6a6ac24bee20759fad5677225ec6
- url: /vibehome
  script: Main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest